# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: simple-node-container
        image: pokfinner/simple-node-project:latest
        ports:
        - containerPort: 3000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-node-service
spec:
  type: LoadBalancer
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
